# CesarOps Search & Rescue Platform - Donation & Sponsorship Accounts
# All proceeds support SAR operations, technology, and community training

# Direct donation platforms
github: festeraeb
patreon: cesarops
ko_fi: cesarops
liberapay: cesarops

# Cryptocurrency (if applicable)
# custom: ["https://donate.cesarops.org"]

# Note: CesarOps is a community-driven SAR platform funded by:
# 1. SonarSniffer professional license sales (100% of proceeds)
# 2. Direct community donations and sponsorships
# 3. Volunteer contributions from SAR teams

# All funds are transparently documented and reported quarterly
# See: https://cesarops.org/funding
