apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sonarsniffer-scaledobject
  namespace: sonarsniffer
spec:
  scaleTargetRef:
    name: sonarsniffer
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
    - type: redis
      metadata:
        address: redis.sonarsniffer.svc.cluster.local:6379
        listName: "sonarsniffer-queue"
        listLength: '5'