apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sonarsniffer-kv-spc
  namespace: sonarsniffer
spec:
  provider: azure
  secretObjects:
    - secretName: sonarsniffer-secrets
      type: Opaque
      data:
        - objectName: SENTRY-DSN
          key: SENTRY_DSN
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: "shipwreck-kv-20260207"
    objects: |
      array:
        - |
          objectName: SENTRY-DSN
          objectType: secret
    tenantId: "248d303d-da77-4073-8a7b-d6640600a793"