; SonarSniffer Windows Installer Script (NSIS format)
; This is generated by Tauri's Windows bundler

!include "MUI2.nsh"
!include "LogicLib.nsh"

; General settings
Name "SonarSniffer"
OutFile "sonarsniffer-0.1.0.exe"
InstallDir "$PROGRAMFILES\SonarSniffer"
InstallDirRegKey HKLM "Software\SonarSniffer" ""

; MUI Settings
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_LANGUAGE "English"

; Installer sections
Section "Install"
  SetOutPath "$INSTDIR"
  File "sonarsniffer.exe"
  File "resources\*.*"
  CreateDirectory "$SMPROGRAMS\SonarSniffer"
  CreateShortCut "$SMPROGRAMS\SonarSniffer\SonarSniffer.lnk" "$INSTDIR\sonarsniffer.exe"
  CreateShortCut "$DESKTOP\SonarSniffer.lnk" "$INSTDIR\sonarsniffer.exe"
SectionEnd

; Uninstaller
Section "Uninstall"
  Delete "$INSTDIR\sonarsniffer.exe"
  Delete "$SMPROGRAMS\SonarSniffer\SonarSniffer.lnk"
  Delete "$DESKTOP\SonarSniffer.lnk"
  RMDir "$SMPROGRAMS\SonarSniffer"
  RMDir "$INSTDIR"
SectionEnd
