{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.keyVault.secretProviderClassName }}
spec:
  provider: azure
  secretObjects:
    - secretName: sonarsniffer-secrets
      type: Opaque
      data:
        - objectName: SENTRY_DSN
          key: SENTRY_DSN
  parameters:
    usePodIdentity: "{{ if .Values.keyVault.useWorkloadIdentity }}true{{ else }}false{{ end }}"
    useVMManagedIdentity: "{{ if .Values.keyVault.useWorkloadIdentity }}false{{ else }}true{{ end }}"
    {{- if .Values.keyVault.useWorkloadIdentity }}
    clientID: "{{ .Values.keyVault.workloadIdentityClientId }}"
    {{- end }}
    keyvaultName: "{{ .Values.keyVault.keyVaultName }}"
    objects: |
      array:
        - |
          objectName: SENTRY_DSN
          objectType: secret
    tenantId: "{{ .Values.keyVault.tenantId }}"
{{- end }}